### ISSUE TITLE
Inclusion to F-Droid?

### ISSUE THREAD

**Issue by ClockGen** [fennifith/Status#116]
F-Droid is a catalogue of free and open source software and is mainly aimed at people who value their privacy and don't want to rely on proprietary services and apps like google, amazon, etc. Status is an awesome app and would definitely fit in the repository. Inclusion policy requires consent of the developer. If you support the idea, I'll fill the inclusion form.

**Comment by TheAndroidMaster** [comment]
Sure, I don't have any problem with it. How do you handle updates? Are they created automatically when I make a new release on github, or do I need to create them through the site somehow?

**Comment by ClockGen** [comment]
Yes, they are automatically checked. More information is here. 
https://f-droid.org/en/docs/Build_Metadata_Reference/#Update-Check-Mode
https://f-droid.org/en/docs/FAQ_-_App_Developers/#do-i-need-to-tell-you-when-i-update

**Comment by ClockGen** [comment]
Opened: https://gitlab.com/fdroid/rfp/issues/495

**Comment by Perflyst** [comment]
There is a comment: `This app requires the me.drozdzynski.library.steppers library but I'm not sure where it gets it from or what version it needs.`

Can you please add these informations to your README.md or answer in the fdroid issue?

**Comment by TheAndroidMaster** [comment]
@Perflyst sure, it's from [drozdzynski/Steppers](https://github.com/drozdzynski/Steppers). I'll put this in the fdroid issue as well. Pretty sure this is known already from #129 though.

**Comment by Perflyst** [comment]
Thanks, to fix the problem and to be able to submit it do F-Droid you need to release a new version due to the build servers only look at the github version tags.
