### ISSUE TITLE
Tagging scheme: 3.8-beta7 or v3.8-beta7?

### ISSUE THREAD

**Issue by relan** [fennifith/Status#160]
The latest version is tagged as 3.8-beta7, but all previous tags had the _v_ prefix. Is this a typo or a new tagging scheme? This is important for F-Droid's autoupdate mechanism.

**Comment by fennifith** [comment]
Sorry for the late response. I honestly can't remember making that release, it was probably late at night when I was half asleep. I can't think of any reason for me to switch tagging schemes, so it was probably just a typo. I will continue using the `v` prefix in the next release.

**Comment by relan** [comment]
OK, thanks.
